# Generated by Django 3.1.2 on 2020-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('data', models.DateField()),
                ('quantidade_saida', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=models.SET('Produto descontinuado'), to='produto.produto')),
                ('usuario', models.ForeignKey(on_delete=models.SET('Usuário Excluído'), to='usuario.usuario')),
            ],
        ),
    ]
