# Generated by Django 3.1.2 on 2020-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_saida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('data', models.DateField()),
                ('quantidade_saida', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
