# Generated by Django 3.1.2 on 2020-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=32)),
                ('tipo_usuario', models.ForeignKey(on_delete=models.SET('Classificação Excluída'), to='tipo_usuario.tipousuario')),
            ],
        ),
    ]
