# Generated by Django 3.1.2 on 2020-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('produto', '0002_auto_20201023_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=models.SET('Categoria Excluída'), to='categoria.categoria'),
        ),
    ]
